name: Update oc.software and trigger oc.user

on:
  repository_dispatch:
    types: dispatch-from-oc.ubuntu
  push:
    branches:
      - main
jobs:
  update_image_oc_software:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 20.04, 21.04]
    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone "https://github.com/abcdesktopio/oc.software.git" .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push oc.software.${{ matrix.BASE_IMAGE_RELEASE }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }}
            BASE_IMAGE=abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}:dev
          tags: |
            abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }}:dev
  dispatch_oc_user:
    needs: update_image_oc_software
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch on repository oc.user
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user
          event-type: dispatch-from-oc.software
