name: Update oc.software and trigger oc.user

on:
  repository_dispatch:
    types: dispatch-from-oc.ubuntu
  push:
    branches:
      - main
jobs:
  update_image_oc_software:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BASE_IMAGE_RELEASE: [18.04, 21.04]
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          build-args: |
            TAG=dev
            BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }}
            BASE_IMAGE=abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }}
          tags: |
            abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }}:dev
            
 
      # - name: Run Buildx oc.software.${{ matrix.BASE_IMAGE_RELEASE }}
      #  run: |
      #    docker buildx build \
      #      --build-arg BASE_IMAGE_RELEASE=${{ matrix.BASE_IMAGE_RELEASE }} \
      #      --build-arg BASE_IMAGE=abcdesktopio/oc.ubuntu.${{ matrix.BASE_IMAGE_RELEASE }} \
      #      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
      #      --platform linux/amd64,linux/arm/v7,linux/arm64 \
      #      --output "type=image,push=true" \
      #      --tag abcdesktopio/oc.software.${{ matrix.BASE_IMAGE_RELEASE }}:dev \
      #      --file ./Dockerfile .
            
  dispatch_oc_user:
    needs: update_image_oc_software
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch on repository oc.user
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.user
          event-type: dispatch-from-oc.software
